FROM ubuntu:noble

RUN apt-get update && \
    apt-get install -y python3.12 python3.12-venv && \
    rm -rf /var/lib/apt/lists/*

RUN python3.12 -m venv .venv && \
    .venv/bin/pip install pyperformance

ENTRYPOINT [".venv/bin/pyperformance", "run", "-b"]
CMD ["nbody"]
