FROM ubuntu:oracular

RUN apt-get update && \
    apt-get install -y python3.13 python3.13-venv && \
    rm -rf /var/lib/apt/lists/*

RUN python3.13 -m venv .venv && \
    .venv/bin/pip install pyperformance

ENTRYPOINT [".venv/bin/pyperformance", "run", "-b"]
CMD ["nbody"]
